services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454/udp"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      VERSION: ${VERSION}
      TYPE: CUSTOM
      RCON_PASSWORD: ${RCON_PASSWORD}
      ENABLE_WHITELIST: "TRUE"
      CUSTOM_JAR_EXEC: "-jar /spigot/server.jar"
      PLUGINS: |
        https://cdn.modrinth.com/data/1QZbMb72/versions/FcgboFDT/Keep-Inv-Individual-1.4.3.jar
        https://cdn.modrinth.com/data/9eGKb6K1/versions/tA5pALYl/voicechat-bukkit-2.5.25.jar
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    depends_on:
      spigot:
        condition: service_healthy
    volumes:
      - ./data:/data
      - ./spigot:/spigot
  whitelistbot:
    build: /bot
    command: ["npm", "run", "bot"]
    depends_on:
      mc:
        condition: service_healthy
  spigot:
    build:
      context: ./spigot
      args:
        - VERSION=${VERSION}
    env_file:
      - .env
    command: sh -c "cp /buildtools/server.jar /spigot/server.jar && tail -F /spigot/server.jar"
    healthcheck:
      test: sh -c "[ -f /spigot/server.jar ]"
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
    volumes:
      - ./spigot:/spigot